Get http://localhost:8000
###

# 创建应用
POST http://localhost:8000/api/app/create
Content-Type: application/json

{
    "app_id": "new2_app",
    "name": "some_app"
}
###

# 获取所有应用
GET http://localhost:8000/api/app/list
###

# 创建应用集群
POST http://localhost:8000/api/cluster/create
Content-Type: application/json

{
    "app_id": "new2_app",
    "cluster": "app_cluster"
}
###

# 重置应用集群 secret
PUT http://localhost:8000/api/cluster/secret/reset
Content-Type: application/json

{
    "app_id": "some_app",
    "cluster": "app_cluster"
}
###


# 获取应用集群
GET  http://localhost:8000/api/cluster/list?app_id=some_app
###

# 创建应用所属 namespace 
POST http://localhost:8000/api/app_ns/create
Content-Type: application/json

{
    "app_id": "new_test_application2",
    "namespace": "app_namespaces1"
}
###

# 获取应用所属 namespace 
GET  http://localhost:8000/api/app_ns/list?
###

# 创建集群所属 namespace 
POST http://localhost:8000/api/namespace/create
Content-Type: application/json

{
    "app_id": "some_app",
    "cluster": "app_cluster",
    "namespace": "namespaces2"
}
###

GET  http://localhost:8000/api/namespace/list?app_id=some_app&cluster=app_cluster
###

POST http://localhost:8000/api/item/create
Content-Type: application/json

{
    "id": "5YN9gPG5VXZM63A1",
    "key": "some keyx1",
    "value": "some value",
    "category": "",
    "remark": "item functional test"
}
###

POST http://localhost:8000/api/item/edit
Content-Type: application/json

{
    "id": "5YN9gPG5VXZM63A1",
    "key": "test2",
    "value": "update new value",
    "category": "",
    "remark": "item functional test",
    "version": 4
}
###

GET  http://localhost:8000/api/item/list?namespace=pVJkzEGBl4bWwZ0x
###

// 发布配置
POST http://localhost:8000/api/item/publish
Content-Type: application/json

{
    "operation": "publish",
    "items": [{
        "id": "5YN9gPG5VXZM63A1",
        "version": 5,
        "remark": "test"
    },
    {
        "id": "kq18VPyWR4ajwNBp",
        "version": 1,
        "remark": "testha"
    }
    ]
}
###

GET http://localhost:8000/api/item/publish/record?item_id=5YN9gPG5VXZM63A1
###

GET http://localhost:8000/api/config/desc?app_id=app_new_id&cluster=app_new_cluster&namespace=namespaces&secret=0fd1ea91af6b81e27c7a7f780c76724c

###

GET http://localhost:8000/api/config/notifaction?app_id=app_new_id&cluster=app_new_cluster&namespace=namespaces&secret=0fd1ea91af6b81e27c7a7f780c76724c&version=adb9102d55497ac313bc5762baf8644c&timeout=10

###
