[package]
name = "entity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version="1", features = ["derive"] }
chrono = "0.4"
lazy_static = "1.4"
harsh = "0.2"

[dependencies.sea-orm]
version = "0.6"
features = ["macros", "runtime-tokio-native-tls", "debug-print","with-chrono"]
default-features = false

[features]
default = ["sqlx-mysql"]
sqlx-mysql = ["sea-orm/sqlx-mysql"]
sqlx-postgres = ["sea-orm/sqlx-postgres"]